/* Single import point for the Node tests: re-exports the pure (DOM-free) building blocks. */
export { tvCartesianSpecs, tvFunnelSpecFromStages, tvHistogramSpecs } from "./charts/model/cartesian.js";
export { TV_DEFAULT_MARK_COLOR, TV_MAX_POINTS, TV_MAX_SERIES, tvBaseSpec, tvCategories, tvChartFont, tvColorScale, tvColorValues, tvHex, tvLabelsOn, tvMarkColor, tvMarkToken, tvMeasureLabel, tvMeasureMark, tvNumFmt, tvPaneRule, tvSeriesType, tvSum, tvText } from "./charts/model/common.js";
export { buildExcelChartSpecs } from "./charts/model/index.js";
export { tvRoles } from "./charts/model/roles.js";
export { TV_GANTT_MAX_SERIES, tvAxisLayout, tvBoxPlotSpec, tvExcelSerial, tvGanttSpec, tvPieSpec, tvQuantile, tvScatterSpec, tvTreemapSpec, tvWaterfallSpec } from "./charts/model/specialized.js";
export { writeChartData } from "./charts/writer/chart-data.js";
export { CHARTEX_COLORS, CHARTEX_STYLE } from "./charts/writer/chartex-style.js";
export { anchorExXml, chartExXml } from "./charts/writer/chartex.js";
export { AX, C15, CT_CHART, CT_CHARTCOLORS, CT_CHARTEX, CT_CHARTSTYLE, CT_DRAWING, EMPTY_RELS, EMU_PER_PX, NS, REL_CHART, REL_CHARTCOLORS, REL_CHARTEX, REL_CHARTSTYLE, REL_DRAWING } from "./charts/writer/constants.js";
export { axisFmt, catAxis, catXml, chartXml, dLbls, line, markerXml, numCache, plotAreaXml, runProps, serTx, seriesXml, solid, strCache, title, txPr, valAxis, valXml, zeroScaling } from "./charts/writer/drawingml.js";
export { addOverride, addRel, anchorXml, dirOf, injectCharts, insertDrawingTag, nextFreeIndex, nextRelId, relTarget, relsPathOf, resolve } from "./charts/writer/package.js";
export { attr, cellRef, colName, esc, hex, levelStarts, num } from "./charts/writer/xml-util.js";
export { FORMAT_CONFIG, TABLEAU_DEFAULTS, TF_DERIV_LABEL, TF_ELEMENTS, VISUAL_TYPES } from "./config.js";
export { TF_MONTHS, TF_WEEKDAYS, tfCalendarRank, tfDvNum, tfDvText, tfIsNull, tfNaturalCompare } from "./data/values.js";
export { setCellValue, subtitleCell, tableDataCell, tableHeaderCell, thickBorder, thinBorder, titleCell, writeDashboardTitle, writeIndividualFilterTable } from "./export/cell-writers.js";
export { applyConditionalFormattingToTable, getZeroCenteredColor, isGeographicCoordinate, isNumeric, isNumericForFormatting, shouldSkipConditionalFormatting } from "./export/conditional-format.js";
export { CHART_DATA_SHEET, COL_GAP, EXCEL_COL_PX, EXCEL_ROW_PX, PX_PER_COL, PX_PER_ROW, ROW_GAP, ROW_GROUP_THRESHOLD, TITLE_ROWS, buildLayoutMap, getExcelColumnName, graphicBox, makeRangeTracker, resolveCollisions, viewModelHeight } from "./export/layout.js";
export { extractFilterValuesPerField, fetchAllSheetsData, isFilterValueWorksheet } from "./export/sheet-data.js";
export { applyAutoFilters, borderSide, buildColorPlan, setColumnWidths, writeKPICardStacked, writeRegularTable, writeTableauTitle } from "./export/visual-writers.js";
export { tfBuildColorScale } from "./format/color-scale.js";
export { tfArgb, tfBrightness, tfInterpolate, tfSample } from "./format/colors.js";
export { tfExcelAlignment, tfExcelFill, tfExcelFont, tfRichRuns, tfWriteCell } from "./format/excel-style.js";
export { inferExcelNumFmt, tableauToExcelNumFmt, tfConvertSection, tfSplitSections } from "./format/number-format.js";
export { AUTOMATIC_PALETTE_BY_MARK, DEFAULT_AUTOMATIC_PALETTE, TABLEAU_10, TABLEAU_BUILTIN_PALETTES, getAutomaticPaletteForMark, getBuiltInPaletteColors } from "./format/palettes.js";
export { TF_ZONE_TOL, tfDashboardTitleRuns, tfStrokeToBorder, tfTextBoxHeaders, tfZoneText } from "./twb/dashboard-text.js";
export { tfExtractRefs, tfParseFieldRef, tfRefKey, tfSameField } from "./twb/field-ref.js";
export { createSheetFormatter, tfCollect, tfDisplayNames, tfFieldInfo, tfFormatsToProps, tfMerge } from "./twb/formatter.js";
export { parseTableauFormatting, tfBucketKey, tfDebugDump, tfParseColorEncoding, tfParseRunProps, tfParseRuns, tfParseStyle, tfParseTitle } from "./twb/parser.js";
export { tfDefined, tfKid, tfKids, tfLog, tfNorm, tfNum } from "./util.js";
export { TV_DATE_DERIVS, classifyVisualType, isKPIViewModel, liveSpecShape, normalizeVisualToken, resolveVisualMarks, tvIsMeasureRef, visualShelfShape, visualSpecMarkTokens } from "./visual/classify.js";
export { VIZ_IMAGE_DISCRETE_PALETTES, VIZ_IMAGE_ORDER_FIELD, buildVizImageSpec, renderTableauImage, svgToPngDataUrl } from "./visual/image-renderer.js";
export { buildViewModel } from "./visual/view-model.js";
export { VISUAL_RENDERERS, buildVisualModel, chooseVisualRenderer, imageOrFallback } from "./visual/visual-model.js";
export { checkWorkbookMatch, describeWorkbookMatch } from "./visual/workbook-match.js";
export { ExcelChartWriter } from "./charts/writer/index.js";
